host: sgnlp.aisingapore.net

ui:
  name: ui
  port: 8080
  image: asia.gcr.io/infra-public-hosting/sgnlp/sgnlp-ui:latest
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"

docs:
  name: docs
  port: 80
  image: asia.gcr.io/infra-public-hosting/sgnlp/docs:latest
  resources:
    requests:
      memory: "100Mi"
      cpu: "100m"

models:
  lsr:
    name: lsr
    port: 8000
    path: /api/relation-extraction/lsr/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: asia.gcr.io/infra-public-hosting/sgnlp/lsr:latest
    resources:
      requests:
        memory: "5Gi"
        cpu: "800m"
    healthcheck: true
  recconSpanExtraction:
    name: span-extraction
    port: 8000
    path: /api/span-extraction/spanbert/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: asia.gcr.io/infra-public-hosting/sgnlp/reccon-span-extraction:latest
    resources:
      requests:
        memory: "4Gi"
        cpu: "250m"
    healthcheck: true
  recconEmotionEntailment:
    name: emotion-entailment
    port: 8000
    path: /api/emotion-entailment/roberta-base/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: asia.gcr.io/infra-public-hosting/sgnlp/reccon-emotion-entailment:latest
    resources:
      requests:
        memory: "3Gi"
        cpu: "250m"
    healthcheck: true
  rumourDetectionTwitter:
    name: rumour-detection-twitter
    port: 8000
    path: /api/rumour-detection-twitter/rumour-detection-twitter/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: asia.gcr.io/infra-public-hosting/sgnlp/rumour-detection-twitter:latest
    resources:
      requests:
        memory: "1Gi"
        cpu: "250m"
    healthcheck: true
  grammaticalErrorCorrection:
    name: csgec
    port: 8000
    path: /api/grammatical-error-correction/csgec/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: asia.gcr.io/infra-public-hosting/sgnlp/csgec:latest
    resources:
      requests:
        memory: "2.5Gi"
        cpu: "500m"
    healthcheck: true
  rstPointer:
    name: rst-pointer
    port: 8000
    path: /api/discourse-parsing/rst-pointer/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: asia.gcr.io/infra-public-hosting/sgnlp/rst-pointer:latest
    resources:
      requests:
        memory: "2Gi"
        cpu: "500m"
    healthcheck: true
  lif3wayAp:
    name: lif-3way-ap
    port: 8000
    path: /api/identify-follow-up-question/lif-3way-ap/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: asia.gcr.io/infra-public-hosting/sgnlp/lif-3way-ap:latest
    resources:
      requests:
        memory: "500Mi"
        cpu: "250m"
  ufd:
    name: ufd
    port: 8000
    path: /api/cross-lingual-cross-domain/ufd/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: asia.gcr.io/infra-public-hosting/sgnlp/ufd:latest
    resources:
      requests:
        memory: "4Gi"
        cpu: "500m"
  senticGcn:
    name: sentic-gcn
    port: 8000
    path: /api/aspect-based-sentiment-analysis/sentic-gcn/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: asia.gcr.io/infra-public-hosting/sgnlp/sentic-gcn:latest
    resources:
      requests:
        memory: "2.5Gi"
        cpu: "500m"
  coherenceMomentum:
    name: coherence-momentum
    port: 8000
    path: /api/coherence-modeling/coherence-momentum/(.*)
    rewriteTarget: /$1
    replicas: 1
    image: asia.gcr.io/infra-public-hosting/sgnlp/coherence-momentum:latest
    resources:
      requests:
        memory: "3Gi"
        cpu: "500m"